### ISSUE TITLE
Redis Cluster Import Error

### ISSUE THREAD

**Issue by DustinMoriarty** [Richard-Mathie/Flask-Cache-Redis-Cluster#7]
When CACHE_TYPE is set to rediscluster, an import error occurs.

```bash
  File "/path/to/lib/python3.8/site-packages/flask_caching/__init__.py", line 220, in _set_cache
    raise ImportError(
ImportError: rediscluster is not a valid Flask-Caching backend
```

Upon further inspection, it appears that for some reason rediscluster cannot be imported from flask_caching.backend.
```python
>>> from flask_caching.backends import redis
>>> redis
<function redis at 0x7fcf55339af0>
>>> from flask_caching.backends import rediscluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'rediscluster' from 'flask_caching.backends' (/path/to/lib/flask_caching/backends/__init__.py)
```

However, rediscluster should be a function at flask_caching/backends line 120 of release 1.9.0. I am still trying to determine what is different between redis and rediscluster which would make redis cluster not import.

It should be noted that this error only occurs when the package is installed from a build. It does not occur when the package is installed from source in editable mode.

**Comment by DustinMoriarty** [comment]
My apologies. I raised this in the wrong repo. Closing the issue.
